configfile: "config/config.yaml"

wildcard_constraints:
    experiment= "|".join(x for x in config.get("cellranger_matrices").keys()),
    subset= "germ_cell",

include: "rules/cellranger-import.smk"
include: "rules/single-cell-preproc.smk"
include: "rules/germ_cells.smk"
include: "rules/plots.smk"
include: "rules/differential_expression.smk"

rule all:
    input:
        expand("results/cellranger-import/{x}.sce.assigned.rds",x=config.get("cellranger_matrices")),
        expand("results/preprocessing/{x}.sce.passing_cells.rds",x=config.get("cellranger_matrices")),
        "results/integration/adult.sce.integrated.rds",
        "results/integration/adult.sce.integrated.clustered.rds",
        "results/integration/adult.sce.integrated.clustered.celltypes.rds",
        "results/germ_cells/adult.sce.integrated.clustered.celltypes.germ_cell.rds",
        "results/germ_cells/adult.sce.integrated.clustered.celltypes.germ_cell.reprocessed.rds",
        "results/differential_expression/adult.tbl.pseudobulk.de.tsv.gz",

        # plots
        rules.plot_germ_and_somatic_pca.output,
        'results/plots/cluster_label_correlation_matrices/cluster_label_correlation_matrix.jain_vs_green2018.pdf',