configfile: "config/config.yaml"

wildcard_constraints:
    experiment= "|".join(x for x in config.get("cellranger_matrices").keys()),
    subset= "germ_cell",

include: "rules/cellranger-import.smk"
include: "rules/single-cell-preproc.smk"
include: "rules/subsets.smk"
include: "rules/plots.smk"
include: "rules/differential_expression.smk"

rule all:
    input:
        expand("results/cellranger-import/{x}.sce.assigned.rds",x=config.get("cellranger_matrices")),
        expand("results/preprocessing/{x}.sce.passing_cells.rds",x=config.get("cellranger_matrices")),
        "results/integration/adult.sce.integrated.rds",
        "results/integration/adult.sce.integrated.clustered.rds",
        "results/integration/adult.sce.integrated.clustered.celltypes.rds",
        "results/subsets/adult.sce.integrated.clustered.celltypes.germ_cell.rds",
        "results/differential_expression/adult.tbl.pseudobulk.de.tsv.gz",

        # plots
        rules.plot_germ_and_somatic_pca.output,