genes: data/genes.gtf.gz
te_sequences: data/dfam_sequences.fasta

cellranger_matrices:
  juvenile_13d_wt_null: data/cellranger/juvenile_13d_wt_null/raw_feature_bc_matrix/
  adult_9646_combined: data/cellranger/adult_9646/raw_feature_bc_matrix/
  adult_9682_combined: data/cellranger/adult_9682/raw_feature_bc_matrix/

cellranger_cmo_assignment:
  juvenile_13d_wt_null: data/cellranger/juvenile_13d_wt_null/assignment_confidence_table.csv
  adult_9646_combined: data/cellranger/adult_9646/assignment_confidence_table.csv
  adult_9682_combined: data/cellranger/adult_9682/assignment_confidence_table.csv

celltype_assignment:
  juvenile_13d_wt_null: data/celltype_classification_per_barcode.csv # from umich collabs

garnett_classifier:
  adult_9646_combined: data/green2018_garnett_adult_testis_classifier.txt
  adult_9682_combined: data/green2018_garnett_adult_testis_classifier.txt
  adult: data/green2018_garnett_adult_testis_classifier.txt