genes: data/genes.gtf.gz
te_sequences: data/dfam_sequences.fasta

cellranger_matrices:
  adult_9646_1: data/cellranger/adult_9646_1/raw_feature_bc_matrix/
  adult_9646_2: data/cellranger/adult_9646_2/raw_feature_bc_matrix/
  adult_9682_1: data/cellranger/adult_9682_1/raw_feature_bc_matrix/
  adult_9682_2: data/cellranger/adult_9682_2/raw_feature_bc_matrix/

cellranger_cmo_assignment:
  adult_9646_1: data/cellranger/adult_9646_1/assignment_confidence_table.csv
  adult_9646_2: data/cellranger/adult_9646_2/assignment_confidence_table.csv
  adult_9682_1: data/cellranger/adult_9682_1/assignment_confidence_table.csv
  adult_9682_2: data/cellranger/adult_9682_2/assignment_confidence_table.csv

garnett_classifier:
  broad: data/green2018_garnett_adult_testis_classifier.txt


dfam_te_classifications: data/dfam_classification.parsed.txt

cell_cycle_genes: data/macosko2015_supp2.xlsx

msigdb: data/m5.go.bp.v2023.2.Mm.symbols.gmt

gc_subclusters_k:
  Spermatogonia: 2
  Spermatocyte: 2
  RoundSpermatid: 3
  Elongating: 1