genes: data/genes.gtf.gz
te_sequences: data/dfam_sequences.fasta

groupings:
  adult: ['adult1', 'adult2', 'adult3', 'adult4']
  juvenile: ['juvenile_13d_wt_null']


cellranger_matrices:
  juvenile_13d_wt_null: data/cellranger/custom/raw_feature_bc_matrix/
  adult_9646_1:
  adult_9646_2:
  adult_9682_1:
  adult_9682_2:
  adult1: data/cellranger/custom_adult/adult1/raw_feature_bc_matrix.h5
  adult2: data/cellranger/custom_adult/adult2/raw_feature_bc_matrix.h5
  adult3: data/cellranger/custom_adult/adult3/raw_feature_bc_matrix.h5
  adult4: data/cellranger/custom_adult/adult4/raw_feature_bc_matrix.h5

cellranger_filtered_matrices:
  adult1: data/cellranger/custom_adult/adult1/filtered_feature_bc_matrix.h5
  adult2: data/cellranger/custom_adult/adult2/filtered_feature_bc_matrix.h5
  adult3: data/cellranger/custom_adult/adult3/filtered_feature_bc_matrix.h5
  adult4: data/cellranger/custom_adult/adult4/filtered_feature_bc_matrix.h5

cellranger_cmo_assignment:
  juvenile_13d_wt_null: data/cellranger/custom/assignment_confidence_table.csv

celltype_assignment:
  juvenile_13d_wt_null: data/celltype_classification_per_barcode.csv